service: hello-retail

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  versionFunctions: false
  region: ${env:REGION}
  environment:
    EPSAGONTOKEN: ${env:EPSAGONTOKEN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "lambda:InvokeFunction"
            - "lambda:InvokeAsync"
          Resource: arn:aws:lambda:us-east-2:*:*
  

functions:
  product-purchase:
    handler: ./hello-retail/product-purchase/handler.main
    timeout: 900
  product-purchase-authorize-cc:
    handler: ./hello-retail/product-purchase-authorize-cc/handler.main
    timeout: 900
  product-purchase-get-price:
    handler: ./hello-retail/product-purchase-get-price/handler.main
    timeout: 900
  product-purchase-publish:
    handler: ./hello-retail/product-purchase-publish/handler.main
    timeout: 900
