service: hello-retail

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: ${env:MEMORY_SIZE}
  versionFunctions: false
  region: ${env:REGION}
  environment:
    REGION: ${env:REGION}
    EPSAGONTOKEN: ${env:EPSAGONTOKEN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "lambda:InvokeFunction"
            - "lambda:InvokeAsync"
          Resource: arn:aws:lambda:us-east-2:*:*


functions:
  product-purchase:
    handler: ./hello-retail/product-purchase/handler.main
    timeout: ${env:TIMEOUT}
    environment:
      GETPRICE: ${env:REGION}
      AUTHORIZECC: ${env:REGION}
      PUBLISH: ${env:REGION}
  product-purchase-get-price:
    handler: ./hello-retail/product-purchase-get-price/handler.main
    timeout: ${env:TIMEOUT}
  product-purchase-authorize-cc:
    handler: ./hello-retail/product-purchase-authorize-cc/handler.main
    timeout: ${env:TIMEOUT}
  product-purchase-publish:
    handler: ./hello-retail/product-purchase-publish/handler.main
    timeout: ${env:TIMEOUT}
